### PR TITLE
Add: NewGeometryWithVAO and InitWithVAO

### PR DESCRIPTION
**Pull request by amyadzuki**
This lets us create a Geometry with our own VAOs.  I intend to use this to allow multiple Geometry objects share VBOs.

### CODE REVIEW

**Comment by danaugrs** [comment]
Why do you need multiple Geometry objects that share a VAO and a set of VBOs? If they don't differ from each other you can just use the same Geometry object in any number of Graphic objects.

**Comment by amyadzuki** [comment]
I may very well be going about this the wrong way, but I wanted a VBO for vertex positions of all the combined "parts" of a human (skin, eyes, hair, etc), another VBO for the UVs for all the combined parts, but then have these parts be selectively enabled by using different sets of indices.  Since indices are in the Geometry, I thought this was the easiest way.

**Comment by danaugrs** [comment]
Ok, that's a valid use case! 😄 I added two methods to the geometry API - `SetVAO` and `VAO` as part of https://github.com/g3n/engine/commit/61cb2ab048fe744cb9b3636c29ed12c027f07a52. Let me know if you need anything further!

**Comment by amyadzuki** [comment]
Perfect, thanks!

**Pull request closed without merging**
