### PR TITLE
postprocessing idea

### PR DESCRIPTION
**Pull request by uzudil**
Hello,

This is a cleaned up version of a previous PR idea: for my project, I'd like to use an old-schooly-pixelated effect by rendering into a texture via an opengl framebuffer. Please let me know if you're planning something like this, or if this PR could be improved in any way.

Here is the example code using the effect:
```go
package main

import (
	"time"

	"github.com/g3n/engine/app"
	"github.com/g3n/engine/camera"
	"github.com/g3n/engine/core"
	"github.com/g3n/engine/geometry"
	"github.com/g3n/engine/gls"
	"github.com/g3n/engine/graphic"
	"github.com/g3n/engine/gui"
	"github.com/g3n/engine/light"
	"github.com/g3n/engine/material"
	"github.com/g3n/engine/math32"
	"github.com/g3n/engine/renderer"
	"github.com/g3n/engine/util/helper"
	"github.com/g3n/engine/window"
)

const (
	Width              = 160
	Height             = 100
	screenShaderVertex = `
		#version 330 core
		layout (location = 0) in vec3 aPos;
		layout (location = 1) in vec3 aColor;
		layout (location = 2) in vec2 aTexCoords;
		
		out vec2 TexCoords;
		
		void main()
		{
			gl_Position = vec4(aPos.x, aPos.y, 0.0, 1.0); 
			TexCoords = aTexCoords;
		} 
	` + "\x00"

	screenShaderFrag = `
		#version 330 core
		out vec4 FragColor;
		
		in vec2 TexCoords;
		
		uniform sampler2D screenTexture;
		
		void main()
		{ 
			if(int(gl_FragCoord.y) % 2 == 0) {
				FragColor = texture(screenTexture, TexCoords);
			} else {
				FragColor = vec4(vec3(0), 1.0);
			}
		}	
	` + "\x00"
)

func main() {

	// Create application and scene
	a := app.App()
	scene := core.NewNode()

	// Set the scene to be managed by the gui manager
	gui.Manager().Set(scene)

	// Create perspective camera
	cam := camera.New(1)
	cam.SetPosition(0, 0, 3)
	scene.Add(cam)

	// Set up orbit control for the camera
	camera.NewOrbitControl(cam)

	// Set up callback to update viewport and camera aspect ratio when the window is resized
	onResize := func(evname string, ev interface{}) {
		// Get framebuffer size and update viewport accordingly
		width, height := a.GetSize()
		a.Gls().Viewport(0, 0, int32(width), int32(height))
		// Update the camera's aspect ratio
		cam.SetAspect(float32(width) / float32(height))
	}
	a.Subscribe(window.OnWindowSize, onResize)
	onResize("", nil)

	// Create a blue box and add it to the scene
	geom := geometry.NewBox(1, 1, 1)
	mat := material.NewStandard(math32.NewColor("DarkBlue"))
	mesh := graphic.NewMesh(geom, mat)
	scene.Add(mesh)

	// Create and add lights to the scene
	scene.Add(light.NewAmbient(&math32.Color{1.0, 1.0, 1.0}, 0.8))
	pointLight := light.NewPoint(&math32.Color{1, 1, 1}, 5.0)
	pointLight.SetPosition(1, 0, 2)
	scene.Add(pointLight)

	// Create and add an axis helper to the scene
	scene.Add(helper.NewAxes(0.5))

	// Set background color to gray
	a.Gls().ClearColor(0.5, 0.5, 0.5, 1.0)

	pp := a.Renderer().CreatePostprocessor(Width, Height, screenShaderVertex, screenShaderFrag)

	// Run the application
	a.Run(func(renderer *renderer.Renderer, deltaTime time.Duration) {
		fbwidth, fbheight := a.IWindow.GetFramebufferSize()
		pp.Render(fbwidth, fbheight, func() {
			a.Gls().Clear(gls.DEPTH_BUFFER_BIT | gls.STENCIL_BUFFER_BIT | gls.COLOR_BUFFER_BIT)
			renderer.Render(scene, cam)
		})
	})
}
```

Thanks!

### CODE REVIEW

**Comment by danaugrs** [comment]
Thanks @uzudil! If you (or anyone) can fix the conflicts and put the postprocessor in a separate file I'll merge this.

**Comment by uzudil** [comment]
Great thanks, I'll take a look at this today.

--Gabor

**Comment by uzudil** [comment]
Done. Please let me know if there are other changes you'd like me to make. Thanks!

**Comment by uzudil** [comment]
Actually, let me see if I can change the contribution to the correct user in the above merges... Please don't merge this yet.

**Comment by uzudil** [comment]
Ok ready to merge now. Thanks again!

**Comment by danaugrs** [comment]
Awesome, thanks!

**Pull request merged**
