### PR TITLE
Added ReadPixels to read current image

### PR DESCRIPTION
**Pull request by moethu**
Hi, I'm building a server-side 3D viewer based on g3n. the server is streaming rendered images to webclients and listens for navigation events to update scenes. In order to capture the current rendered image I used the same approach as @rami-dabain in #105. It would be great to have such a method in the g3n engine.

### CODE REVIEW

**Comment by danaugrs** [comment]
Hi - thanks! I just merged a large branch (WebAssembly support is 90% ready 😄), which caused your PR to conflict. So I went ahead and implemented ReadPixels in this commit: https://github.com/g3n/engine/commit/810f1177e7f2f699101276079faeaae58774bf71
You had `width` and `height` arguments to the C function in the reversed order, so I fixed that along with some other minor things. Let me know if it works for you!

**Comment by moethu** [comment]
thank you, that sounds great, my next question would have been the windowless solution. Got a quick question regarding running multiple instances of g3n in parallel. My current [implementation](https://github.com/moethu/g3nserverside) opens up one g3n app per socket. I had to modify the engine, remove the singleton, to be able to start multiple instances. This works fine so far but I've got an issue when one session closes a window. Looks like the glfw manager gets shut down with it and since there is only one of it, all the other running windows fail with ```panic: NotInitialized: The GLFW library is not initialized```. I guess the windowless solution won't require the glfw manager? So I just have to implement a different solution to inject the mouse events.

**Comment by danaugrs** [comment]
That's a pretty awesome project! 😄 I featured it on the G3N readme: https://github.com/g3n/engine/commit/2d0794113a6ff69afc8ad9e6a832b5aaca907123

The `GlfwWindow` is destroyed here:
https://github.com/g3n/engine/blob/56ad665d24f4b62faef355e76cbe1ed0082fa322/window/glfw.go#L408-L414
I'm thinking you could remove `glfw.Terminate()` from there and call it yourself when your rendering server shuts down. Let me know if that works!

**Comment by moethu** [comment]
Thanks for you support. It worked like a charm, calling ```app.win.Destroy()``` instead of ```app.wmgr.Terminate()``` and then terminating glfw once the server shuts down.
Btw, I renamed it to webg3n: https://vimeo.com/358812535

**Comment by danaugrs** [comment]
Wonderful!

**Pull request closed without merging**
